name: ${name}
version: ${version}
main: com.deathmotion.testplugin.TestPlugin
author: Bram
description: Test plugin
api-version: 1.20
depend:
  - packetevents

commands:
  test:
    description: "Test command"
    usage: /test
    aliases:
      - hello