name: ${name}
version: ${version}
main: com.plugin.template.Main
author: yourName
description: yourDescription

api-version: 1.20

commands:
  test:
    description: "Test command"
    usage: /test
    aliases:
      - hello