name: TemplatePlugin
version: ${version}
main: com.plugin.template.PluginName
api-version: '1.21'
authors: [ Bram ]
description: Your plugin description here.
load: POSTWORLD
commands:
  hello:
    description: Say hello back to the player.
    usage: /hello
    aliases: [ hi, hey ]
